### ISSUE TITLE
Unknown suspecious binary

### ISSUE THREAD

**Issue by rifsxd** [iamlooper/Android-Enhancer#5]
What is packet_sdk for? why is authentication needed for it and why is it sending ip address and network packets to a server?

**Comment by iamlooper** [comment]
Everything about it is in the Disclosure. If you are not comfortable with it then simply don't use Android Enhancer.

**Comment by rifsxd** [comment]
![Screenshot_20241117-125248](https://github.com/user-attachments/assets/dac251f2-d95b-4e5a-a1fc-7c6776fa4c65)
![Screenshot_20241117-125256](https://github.com/user-attachments/assets/a154bde1-2b26-48a6-a575-2e37e6646f72)

**Comment by rifsxd** [comment]
Very poor documentation about the packet_sdk it's basically doesn't even say the module has monetization in the readme, it just simply states a pointless disclosure

**Comment by rifsxd** [comment]
Anyways I got rid of it in my fork
